/*
 * Copyright 2018 Bosch Software Innovations GmbH ("Bosch SI"). All rights reserved.
 */
// Filters
export const NEW_FILTER = "NEW_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";
// Logs
export const CHANGE_SORTING = "CHANGE_SORTING";
export const CALCULATE_LOG_MEMORY = "CALCULATE_LOG_MEMORY";
export const NEW_LOG = "NEW_LOG";
export const REMOVE_OLDEST_LOG = "REMOVE_OLDEST_LOG";
export const REMOVE_ALL_LOGS = "REMOVE_ALL_LOGS";
export const NEW_ERROR = "NEW_ERROR";
// Subs
export const ADDING_SUB = "ADDING_SUB";
export const NEW_SUB = "NEW_SUB";
export const DELETING_SUB = "DELETING_SUB";
export const SUB_DELETED = "SUB_DELETED";
// Settings
export const SUBMIT_SETTINGS = "SUBMIT_SETTINGS";
// Websocket Connection
export const CONNECT_TO_EVENTBUS = "CONNECT_TO_EVENTBUS";
export const EVENTBUS_CONNECTED = "EVENTBUS_CONNECTED";
export const EVENTBUS_DISCONNECTED = "EVENTBUS_DISCONNECTED";
export const HUB_CONNECTED = "HUB_CONNECTED";
export const HUB_DISCONNECTED = "HUB_DISCONNECTED";
export const CONNECTING_FAILED = "CONNECTING_FAILED";
export const EVENTBUS_INIT = "EVENTBUS_INIT";
// Debugging and Dev Tools
export const LOAD_STORE_PRESET = "LOAD_STORE_PRESET";
export const ADD_CUSTOM_NOTIFICATION = "ADD_CUSTOM_NOTIFICATION";
// Registrations
export const CREATING_REG = "CREATING_REG";
export const NEW_REG = "NEW_REG";
export const CREATING_REG_FAILED = "CREATING_REG_FAILED";
export const DELETING_REG = "DELETING_REG";
export const REG_DELETED = "REG_DELETED";
export const DELETING_REG_FAILED = "DELETING_REG_FAILED";
export const UPDATING_REG_INFO = "UPDATING_REG_INFO";
export const UPDATED_REG_INFO = "UPDATED_REG_INFO";
export const UPDATING_REG_INFO_FAILED = "UPDATING_REG_INFO_FAILED";
export const CHANGING_ENABLED = "CHANGING_ENABLED";
export const ENABLED_CHANGED = "ENABLED_CHANGED";

export const CONFIGURING_GATEWAY = "CONFIGURING_GATEWAY";
export const CONFIGURED_GATEWAY = "CONFIGURED_GATEWAY";
export const CONFIGURING_GATEWAY_FAILED = "CONFIGURING_GATEWAY_FAILED ";
export const VIA_PROPERTY_SET = "VIA_PROPERTY_SET";
export const SETTING_VIA_PROPERTY = "SETTING_VIA_PROPERTY";
// Credentials
export const CREATING_CREDENTIAL = "CREATING_CREDENTIAL";
export const NEW_CREDENTIAL = "NEW_CREDENTIAL";
export const CREATING_CREDENTIAL_FAILED = "CREATING_CREDENTIAL_FAILED";
export const DELETING_CREDENTIAL = "DELETING_CREDENTIAL";
export const CREDENTIAL_DELETED = "CREDENTIAL_DELETED";
export const DELETING_CREDENTIAL_FAILED = "DELETING_CREDENTIAL_FAILED";
export const INIT_EMPTY_CREDENTIAL = "INIT_EMPTY_CREDENTIAL";
export const UPDATING_CRED_INFO = "UPDATING_CRED_INFO";
export const UPDATING_CRED_INFO_FAILED = "UPDATING_CRED_INFO_FAILED";
export const CHANGING_CRED_ENABLED = "CHANGING_CRED_ENABLED";
export const ENABLED_CRED_CHANGED = "ENABLED_CRED_CHANGED";
export const UPDATING_CRED_SECRETS = "UPDATING_CRED_SECRETS";
export const UPDATED_CRED_SECRETS = "UPDATED_CRED_SECRETS";
export const UPDATING_CRED_SECRETS_FAILED = "UPDATING_CRED_SECRETS_FAILED";
export const CHANGING_CRED_SECRETS = "CHANGING_CRED_SECRETS";
// Secrets
export const CREATING_SECRET = "CREATING_SECRET";
export const CREATING_SECRET_FAILED = "CREATING_SECRET_FAILED";
export const NOT_ALLOWED_CREATING_SECRET = "NOT_ALLOWED_CREATING_SECRET";
export const NEW_SECRET = "NEW_SECRET";
export const DELETING_SECRET = "DELETING_SECRET";
export const SECRET_DELETED = "SECRET_DELETED";
export const DELETING_SECRET_FAILED = "DELETING_SECRET_FAILED";
// Data Fetching
export const FETCHING_TENANT = "FETCHING_TENANT";
export const TENANT_FETCHED = "TENANT_FETCHED";
export const FETCHING_TENANT_FAILED = "FETCHING_TENANT_FAILED";
export const FETCHING_REGISTRATIONS = "FETCHING_REGISTRATIONS";
export const REGISTRATIONS_FETCHED = "REGISTRATIONS_FETCHED";
export const FETCHING_REGISTRATIONS_FAILED = "FETCHING_REGISTRATIONS_FAILED";
export const FETCHING_CREDENTIALS = "FETCHING_CREDENTIALS";
export const CREDENTIALS_FETCHED = "CREDENTIALS_FETCHED";
export const FETCHING_CREDENTIALS_FAILED = "FETCHING_CREDENTIALS_FAILED";
